on: [push]

jobs:
  hello_world_job:
    runs-on: windows-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: Sri-hari/hello-world-composite-run-steps-action@v3
        with:
          who-to-greet: 'Mona the Octocat '
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: cmd
